command: ["uvicorn", "server.app:app", "--host", "0.0.0.0", "--port", "8000"]
env:
  - name: DB_HOST
    value: "instance-1b1f7a5c-f777-41fd-a5d2-5809b176b84e.database.cloud.databricks.com"
  - name: DB_PORT
    value: "5432"
  - name: DB_NAME
    value: "databricks_postgres"
  - name: DB_SCHEMA
    value: "smartstock_synced"
  - name: DB_USER
    value: "lakebase_demo_app"
  - name: DB_PASSWORD
    value: "lakebasedemo2025"