command: ["uvicorn", "server.app:app", "--host", "0.0.0.0", "--port", "8000"]
env:
  - name: DB_HOST
    value: "instance-1b1f7a5c-f777-41fd-a5d2-5809b176b84e.database.cloud.databricks.com"
  - name: DB_PORT
    value: "5432"
  - name: DB_NAME
    value: "databricks_postgres"
  - name: DB_SCHEMA
    value: "smartstock_synced"
  - name: DB_USER
    value: "lakebase_demo_app"
  - name: DB_PASSWORD
    value: "lakebasedemo2025"
  - name: GENIE_SPACE_ID
    value: "01f0b8993ae91634b351d60035aa7c31"
  - name: DATABRICKS_HOST
    value: "https://fe-vm-nam-nguyen-workspace-classic.cloud.databricks.com/"
  - name: DATABRICKS_TOKEN
    value: ${env.DATABRICKS_TOKEN}