command: ["uvicorn", "server.app:app", "--host", "0.0.0.0", "--port", "8000"]
env:
  - name: DB_HOST
    value: "instance-72647268-1c88-4fce-909c-661bb1f25976.database.cloud.databricks.com"
  - name: DB_PORT
    value: "5432"
  - name: DB_NAME
    value: "databricks_postgres"
  - name: DB_USER
    value: "lakebase_demo_app"
  - name: DB_PASSWORD
    value: "lakebasedemo2025"