command: ["uvicorn", "server.app:app", "--host", "0.0.0.0", "--port", "8000"]
env:
  - name: DB_HOST
    value: "instance-7d1fe7e1-8046-41cf-8829-37ea9c50e71a.database.cloud.databricks.com"
  - name: DB_PORT
    value: "5432"
  - name: DB_NAME
    value: "databricks_postgres"
  - name: DB_USER
    value: "lakebase_demo_app"
  - name: DB_PASSWORD
    value: "lakebasedemo2025"